/* staticData.ts
 * No-backend data loader — fetches static JSON files from /data/*.json
 * generated by the GitHub Actions scraper.
 *
 * Usage:
 *   import { loadMovies, loadSeries, loadLatest, searchCatalog } from '@/lib/staticData';
 *
 *   const { items, total } = await loadMovies();
 *   const results = searchCatalog(items, 'search query');
 */

export interface StaticItem {
  id: string;
  title?: string;
  original_title?: string;
  titleAr?: string;
  content_type?: string;
  page_url?: string;
  year?: number;
  genres?: string[];
  language?: string;
  country?: string;
  quality?: string;
  rating?: number;
  duration?: string;
  description?: string;
  cast?: string[];
  director?: string;
  poster_image_url?: string;
  streaming_urls?: string[];
  download_urls?: string[];
  embed_urls?: string[];
  subtitle_urls?: string[];
  breadcrumbs?: string[];
  category?: string;
  source_domain?: string;
  discovered_at?: string;
  updated_at?: string;
}

export interface StaticResponse {
  total: number;
  updated_at: string;
  items: StaticItem[];
}

const BASE = '/data';

async function fetchJSON<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
  }
  return res.json();
}

export async function loadCatalog(): Promise<StaticResponse> {
  return fetchJSON<StaticResponse>(`${BASE}/catalog.json`);
}

export async function loadMovies(): Promise<StaticResponse> {
  return fetchJSON<StaticResponse>(`${BASE}/movies.json`);
}

export async function loadSeries(): Promise<StaticResponse> {
  return fetchJSON<StaticResponse>(`${BASE}/series.json`);
}

export async function loadLatest(): Promise<StaticResponse> {
  return fetchJSON<StaticResponse>(`${BASE}/latest.json`);
}

/** Client-side fuzzy search over the lightweight search-index.json */
export async function searchCatalog(query: string): Promise<StaticItem[]> {
  const data = await fetchJSON<StaticResponse>(`${BASE}/search-index.json`);
  const q = query.toLowerCase().trim();
  if (!q) return data.items;
  return data.items.filter((item) => {
    const title = (item.title || '').toLowerCase();
    const titleAr = (item.titleAr || '').toLowerCase();
    const original = (item.original_title || '').toLowerCase();
    const genres = (item.genres || []).join(' ').toLowerCase();
    return (
      title.includes(q) ||
      titleAr.includes(q) ||
      original.includes(q) ||
      genres.includes(q)
    );
  });
}
